//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest02Map
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentInfo
    {
        public int dId { get; set; }
        public int dTId { get; set; }
        public string dName { get; set; }
        public string dContent { get; set; }
        public Nullable<System.DateTime> dInTime { get; set; }
        public Nullable<System.DateTime> dEditeTime { get; set; }
        public Nullable<bool> dIsDeleted { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
