//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest02Map
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public studentInfo()
        {
            this.scoreInfoes = new HashSet<scoreInfo>();
        }
    
        public int stuID { get; set; }
        public string stuName { get; set; }
        public Nullable<bool> stuSex { get; set; }
        public Nullable<System.DateTime> stubirthday { get; set; }
        public string stuPhone { get; set; }
        public string stuEmail { get; set; }
        public int stuClassID { get; set; }
    
        public virtual @class @class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scoreInfo> scoreInfoes { get; set; }
    }
}
